### PR TITLE
Fix failing event meter tests

### PR DESCRIPTION
**Pull request by Bark-fa**
This should fix the issue in the ManagesUserBilling trait, tests passed locally

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
@Bark-fa tests still fail it seems: https://github.com/laravel/cashier-stripe/actions/runs/10452831229/job/28942077001

**Comment by Bark-fa** [comment]
I see it's failing on Laravel 10, is there any way I can test this locally? That's a very odd thing

**Comment by driesvints** [comment]
You can use `composer require "illuminate/contracts=^10" --no-update` to install Laravel v10 components to run the test suite.

**Comment by Bark-fa** [comment]
I just did, and the tests pass, is there any difference between what I would have by executing the composer command you gave me and the environment in which the tests are running? and what about the environment where the PR tests are getting evaluated on push?

**Comment by driesvints** [comment]
Did you hook up your stripe testing env? See https://github.com/laravel/cashier-stripe/blob/15.x/.github/CONTRIBUTING.md

**Comment by Bark-fa** [comment]
Yes I made sure of it, also ran it before I added the key just to make sure it throws a different kind of error

**Comment by driesvints** [comment]
Then I don't know what's different besides the PHP versions. In any case we'll need to get this fixed or I'll have to revert all before tomorrow when we do releases.

**Comment by Bark-fa** [comment]
Shot in the dark, but I'll try to call sleep(1) after reporting usage, maybe this has something to do with it, is there a way to keep the next PR open and still run the action?

**Comment by driesvints** [comment]
Yeah just put it in draft and you can play around with it 👍

**Pull request merged**
