### PR TITLE
[14.x] Skip trials when cancelling subscriptions from dashboard

### LINKED ISSUE #1443: Disable subscription entirely when canceling through Stripe Dashboard
When a subscription is cancelled through the Stripe Dashboard or Customer Portal, it's not immediately ended when the subscription is still on a generic trial. See https://github.com/laravel/cashier-stripe/pull/1442.

Maybe a config option for this could be added or a simpler way of setting this.

### PR DESCRIPTION
**Pull request by bkd27**

### CODE REVIEW

**Comment by driesvints** [comment]
I'll have a look later at this.

**Comment by driesvints** [comment]
I did some changes. Now when you add `Cashier::skipTrials()` to your service provider, Cashier Stripe will always skip the (generic) trial when cancelling subscriptions.

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
@bkd27 while working on this I realized we're modifying subscription trials here but what you actually want is to end a customer's generic trial on their user record. Generic trials are a Cashier level thing and cannot be controlled from Stripe. You'll have to implement some custom code using webhooks somehow to get the behavior that you desire.

As for subscription trials you can already end them whenever you wish when cancelling them from the dashboard:

Screenshot 2022-09-26 at 16 05 44

**Comment by bkd27** [comment]
> @bkd27 while working on this I realized we're modifying subscription trials here but what you actually want is to end a customer's generic trial on their user record. Generic trials are a Cashier level thing and cannot be controlled from Stripe. You'll have to implement some custom code using webhooks somehow to get the behaviour that you desire.
> 
> As for subscription trials you can already end them whenever you wish when cancelling them from the dashboard:
> 
> Screenshot 2022-09-26 at 16 05 44

Hi, dries

No, the generic trial is a purely separate thing (That is customer level trial), I am concerned about the subscription trial only, If a subscription is cancelled 'Immediately' in a stripe or via the customer portal, the default behaviour is to if the subscription has a trial on then that should be removed. If that is not then what is the use of cancelling the subscription immediately, 

The code that I added controlling that behaviour via config will be handy for that. 

Let me know if you have further questions on this.

**Comment by driesvints** [comment]
I'm still investigating this. Contacted Stripe and will reply once I know more.

**Comment by driesvints** [comment]
I didn't get to this before my vacation but will pick it up again afterwards.

**Comment by driesvints** [comment]
Hi there, I finally found time to look into this again. I've decided to send in a PR that changes the current behavior in the next major version: https://github.com/laravel/cashier-stripe/pull/1465

While this doesn't help you right now, in the next version it will work as you'd expect. I think also that we shouldn't add an option like this PR to accommodate for a bridge in between the versions so unfortunately you'll need to wait a bit longer before it's changed.

**Pull request closed without merging**
