### PR TITLE
[12.x] Fix missing method on WebhookController

### PR DESCRIPTION
**Pull request by driesvints**
Fixes https://github.com/laravel/cashier-stripe/issues/1079

### CODE REVIEW

**Comment by rabol** [comment]
Seems like the code is lost

**Comment by driesvints** [comment]
@rabol it's not? https://github.com/laravel/cashier-stripe/blob/12.x/src/Http/Controllers/WebhookController.php#L55

**Comment by rabol** [comment]
https://github.com/laravel/cashier-stripe/pull/1080/commits/8199445995a3599ced1cfa6fa190658b3a080bc7

look at the method:

```
public function missingMethod($parameters = [])
    {
        return new Response('Missing event type: '.$parameters['type']);
    }
```

in the original PR

and then look at the current version

```
/**
     * Handle calls to missing methods on the controller.
     *
     * @param  array  $parameters
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function missingMethod($parameters = [])
    {
        return new Response;
    }

```

**Comment by driesvints** [comment]
@rabol you're pointing to code in a test. The method in the `missingMethod` method of the `WebhookController` is suppose to be empty.

**Comment by rabol** [comment]
well, the original bug was that a parameter was passed to the missingMethod, but never used
and the 'fix' was that parameter should be used, e.g. in the Response og Log::info()
 
if the 'missingMethod' don 'report' that something is missing, then it is difficult to figure out which method is missing

**Comment by rabol** [comment]
aha.... go it, one have to create a new controller, and override to capture it

**Comment by driesvints** [comment]
Yes, the parameters is simple there to let anyone who wants to override the method and make use of it.

**Pull request merged**
