### PR TITLE
[14.x] Allow guest checkout

### PR DESCRIPTION
**Pull request by alexgaal**
This PR introduces a simple change of `$owner` in `Checkout` being nullable. This allows developers to implement a anonymous checkout / guest checkout for their applications.

```php
Checkout::anonymous($sessionOptions);
```

### CODE REVIEW

**Comment by alexgaal** [comment]
I just recognized that there will be a null pointer exception and it seems this implementation is not possible.

**Comment by driesvints** [comment]
It's possible. I think this is a good idea. Let me push some changes.

**Comment by driesvints** [comment]
I renamed it to `Checkout::guest($sessionOptions);`.

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
I'm gonna postpone releasing this. I'm working on a few improvements but ain't entirely happy yet with the implementation: https://github.com/laravel/cashier-stripe/pull/1439

**Pull request merged**
